language: python
sudo: false

matrix:
  include:
    - python: '2.7'
      env: 'TOXENV=django111'
    - python: '3.5'
      env: 'TOXENV=django111'
    - python: '3.5'
      env: 'TOXENV=quality'

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export BOKCHOY_HEADLESS=true

addons:
  firefox: latest

services:
  - xvfb

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success: coveralls
